# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d21ed95e5ed362335b748f88b2b2c7bf0635d029805c647f69abc64b93a8c9e5d2e8be4802f81abe3d2012a18da3e8409d1012fc8cbee30bc6d34a03e89ac0

test:
  secret_key_base: fe6cdb529dae71895db1d70647a350b879f43e3be12abda646bcc48e81ad9322ca8efd4c324f0f6de9a5c66b74af6ebbeebfb1b4133cef378188aa18e9cce5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
